### ISSUE TITLE
django.db.utils.ProgrammingError: relation "accounts_account" does not exist LINE 1: DELETE FROM "accounts_account"

### ISSUE THREAD

**Issue by TheBrokenWasp** [thenewboston-developers/Bank#89]
So I decided that since setting up a CV isn't going so well, I could try setting up a bank instead. I made a new DB in postgresql, as I had postgresql left over from the validator, and updated the engine and info and stuff in the settings of the file. After running, I get this:
```
root@voy4ge:/Bank# python3 manage.py initialize_test_bank -ip 185.22.172.130
Installing fixture data...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "accounts_account" does not exist
LINE 1: DELETE FROM "accounts_account"
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Bank/v1/self_configurations/management/commands/initialize_test_bank.py", line 55, in handle
    self.install_fixture_data()
  File "/Bank/v1/self_configurations/management/commands/initialize_test_bank.py", line 71, in install_fixture_data
    Account.objects.all().delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 747, in delete
    deleted, _rows_count = collector.delete()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/deletion.py", line 410, in delete
    count = qs._raw_delete(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 763, in _raw_delete
    cursor = query.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "accounts_account" does not exist
LINE 1: DELETE FROM "accounts_account"
```
Note: I did this because SQLite was having trouble as well so I wanted to just recycle PostgreSQL

I am sorry for the noob posts on both here and the validator github, I just want to contribute to the network and get involved and since there is no other good place for discussions about this (as far as I can tell) like a discord server, I have to come to the github pages to ask for help by posting an issue... Sorry.

**Comment by TheBrokenWasp** [comment]
Nvm I found the deployment guide, my bad.

**Comment by anirbanchakraborty123** [comment]
what was the solution

**Comment by anirbanchakraborty123** [comment]
?

**Comment by xcenai** [comment]
> ?

ikr

hate when people dont post the solution
